version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "8100:80"  # 호스트의 8100 포트를 컨테이너의 80 포트로 매핑
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # nginx 설정 파일 매핑
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
    networks:
      - lb_network

  backend1:
    build: ./app
    container_name: backend1
    environment:
      - PORT=5000
    networks:
      - lb_network

  backend2:
    build: ./app
    container_name: backend2
    environment:
      - PORT=5000
    networks:
      - lb_network

  backend3:
    build: ./app
    container_name: backend3
    environment:
      - PORT=5000
    networks:
      - lb_network

  backend4:
    build: ./app
    container_name: backend4
    environment:
      - PORT=5000
    networks:
      - lb_network

networks:
  lb_network:
    driver: bridge
